import type {Metadata} from 'next';
import {AntdRegistry} from '@ant-design/nextjs-registry';
import './globals.css';

export const metadata: Metadata = {
    title: '首页',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
    params: {lng}
}: Readonly<{
  children: React.ReactNode;
  params: { lng: string }
}>) {
    return (
        <html lang={lng}>
            <body>
                <AntdRegistry>{children}</AntdRegistry>
            </body>
        </html>
    );
}
